# Generated by Django 3.2 on 2024-03-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
